import { User, Tag, SubscriptionRequest, CeoReview, HrAction } from './types'

export const MOCK_USERS: User[] = [
  { id: 'u1', name: 'Alice Kim', email: 'alice@company.com', role: 'employee', department: 'Engineering', initials: 'AK' },
  { id: 'u2', name: 'Bob Martinez', email: 'bob@company.com', role: 'employee', department: 'Sales', initials: 'BM' },
  { id: 'u3', name: 'Carol White', email: 'carol@company.com', role: 'employee', department: 'Marketing', initials: 'CW' },
  { id: 'u4', name: 'David Park', email: 'david@company.com', role: 'employee', department: 'Engineering', initials: 'DP' },
  { id: 'ceo1', name: 'Michael Chen', email: 'michael@company.com', role: 'ceo', department: 'Executive', initials: 'MC' },
  { id: 'hr1', name: 'Emily Rodriguez', email: 'emily@company.com', role: 'hr', department: 'Human Resources', initials: 'ER' },
]

export const MOCK_TAGS: Tag[] = [
  { id: 't1', name: 'Engineering', color: '#3b82f6', createdBy: 'hr1', createdAt: '2024-01-10T00:00:00Z' },
  { id: 't2', name: 'Sales', color: '#22c55e', createdBy: 'hr1', createdAt: '2024-01-10T00:00:00Z' },
  { id: 't3', name: 'Marketing', color: '#a855f7', createdBy: 'hr1', createdAt: '2024-01-10T00:00:00Z' },
  { id: 't4', name: 'Operations', color: '#f97316', createdBy: 'hr1', createdAt: '2024-01-15T00:00:00Z' },
  { id: 't5', name: 'Finance', color: '#eab308', createdBy: 'hr1', createdAt: '2024-01-20T00:00:00Z' },
]

export const MOCK_REQUESTS: SubscriptionRequest[] = [
  {
    id: 'req1',
    employeeId: 'u1',
    platformName: 'GitHub Copilot',
    platformUrl: 'https://github.com/features/copilot',
    gmail: 'alice.work@gmail.com',
    gmailPassword: 'SecurePass123!',
    price: 19,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'processed',
    reasonNote: 'Need AI coding assistant to improve development speed and code quality across the team.',
    createdAt: '2024-01-15T09:00:00Z',
    updatedAt: '2024-01-17T14:00:00Z',
  },
  {
    id: 'req2',
    employeeId: 'u2',
    platformName: 'Salesforce CRM',
    platformUrl: 'https://salesforce.com',
    gmail: 'bob.sales@gmail.com',
    gmailPassword: 'SalesForce@456',
    price: 150,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'processed',
    reasonNote: 'CRM tool essential for managing client relationships and sales pipeline tracking.',
    createdAt: '2024-01-16T10:00:00Z',
    updatedAt: '2024-01-18T11:00:00Z',
  },
  {
    id: 'req3',
    employeeId: 'u3',
    platformName: 'Adobe Creative Suite',
    platformUrl: 'https://adobe.com/creativecloud',
    gmail: 'carol.design@gmail.com',
    gmailPassword: 'AdobeCC789!',
    price: 54.99,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'approved',
    reasonNote: 'Required for creating marketing materials, social media content and brand assets.',
    createdAt: '2024-01-20T08:00:00Z',
    updatedAt: '2024-01-21T16:00:00Z',
  },
  {
    id: 'req4',
    employeeId: 'u1',
    platformName: 'Figma Team',
    platformUrl: 'https://figma.com',
    gmail: 'alice.figma@gmail.com',
    gmailPassword: 'FigmaDesign!1',
    price: 45,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'processed',
    reasonNote: 'Collaborative design tool for UI/UX design, prototyping and developer handoff.',
    createdAt: '2024-01-18T11:00:00Z',
    updatedAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'req5',
    employeeId: 'u4',
    platformName: 'Slack Pro',
    platformUrl: 'https://slack.com/intl/pricing',
    gmail: 'david.eng@gmail.com',
    gmailPassword: 'SlackPro@22',
    price: 7.25,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'pending',
    reasonNote: 'Upgrade to Pro for unlimited message history and better integrations with dev tools.',
    createdAt: '2024-01-25T13:00:00Z',
    updatedAt: '2024-01-25T13:00:00Z',
  },
  {
    id: 'req6',
    employeeId: 'u4',
    platformName: 'AWS Developer',
    platformUrl: 'https://aws.amazon.com',
    gmail: 'david.aws@gmail.com',
    gmailPassword: 'AWSCloud@33',
    price: 299,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'declined',
    reasonNote: 'Need cloud infrastructure for running microservices and CI/CD deployments.',
    createdAt: '2024-01-22T14:00:00Z',
    updatedAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'req7',
    employeeId: 'u2',
    platformName: 'HubSpot Marketing Hub',
    platformUrl: 'https://hubspot.com',
    gmail: 'bob.hub@gmail.com',
    gmailPassword: 'HubSpot@456',
    price: 890,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'pending',
    reasonNote: 'Marketing automation platform for managing campaigns and lead generation at scale.',
    createdAt: '2024-01-26T09:00:00Z',
    updatedAt: '2024-01-26T09:00:00Z',
  },
  {
    id: 'req8',
    employeeId: 'u3',
    platformName: 'Notion Team',
    platformUrl: 'https://notion.so/pricing',
    gmail: 'carol.notion@gmail.com',
    gmailPassword: 'NotionTeam!2',
    price: 16,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'approved',
    reasonNote: 'Team wiki and project management for marketing team documentation and coordination.',
    createdAt: '2024-01-24T15:00:00Z',
    updatedAt: '2024-01-25T11:00:00Z',
  },
  {
    id: 'req9',
    employeeId: 'u1',
    platformName: 'Zoom Pro',
    platformUrl: 'https://zoom.us/pricing',
    gmail: 'alice.zoom@gmail.com',
    gmailPassword: 'ZoomPro@789',
    price: 14.99,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'pending',
    reasonNote: 'Need Pro plan for longer meeting durations when meeting with external clients and partners.',
    createdAt: '2024-01-27T10:00:00Z',
    updatedAt: '2024-01-27T10:00:00Z',
  },
  {
    id: 'req10',
    employeeId: 'u4',
    platformName: 'Linear',
    platformUrl: 'https://linear.app/pricing',
    gmail: 'david.linear@gmail.com',
    gmailPassword: 'LinearApp!4',
    price: 8,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'processed',
    reasonNote: 'Issue tracking and sprint management for our engineering team workflows.',
    createdAt: '2024-01-19T12:00:00Z',
    updatedAt: '2024-01-21T15:00:00Z',
  },
  {
    id: 'req11',
    employeeId: 'u2',
    platformName: 'LinkedIn Sales Navigator',
    platformUrl: 'https://linkedin.com/sales',
    gmail: 'bob.linkedin@gmail.com',
    gmailPassword: 'LinkedIn@789',
    price: 99.99,
    currency: 'USD',
    billingCycle: 'monthly',
    status: 'processed',
    reasonNote: 'Sales prospecting tool for finding and connecting with potential clients and leads.',
    createdAt: '2024-01-14T09:00:00Z',
    updatedAt: '2024-01-16T11:00:00Z',
  },
  {
    id: 'req12',
    employeeId: 'u3',
    platformName: 'Canva Pro',
    platformUrl: 'https://canva.com/pro',
    gmail: 'carol.canva@gmail.com',
    gmailPassword: 'CanvaPro@11',
    price: 12.99,
    currency: 'USD',
    billingCycle: 'yearly',
    status: 'declined',
    reasonNote: 'Design platform for quick social media graphics without needing Figma or Adobe.',
    createdAt: '2024-01-12T11:00:00Z',
    updatedAt: '2024-01-13T09:00:00Z',
  },
]

export const MOCK_CEO_REVIEWS: CeoReview[] = [
  {
    id: 'rev1',
    requestId: 'req1',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'GitHub Copilot significantly boosts developer productivity. The monthly cost is justified by the time savings. Approved for the engineering team.',
    reviewedAt: '2024-01-16T10:00:00Z',
  },
  {
    id: 'rev2',
    requestId: 'req2',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'Salesforce is critical for our sales operations. This is a strategic tool that directly impacts revenue. Approved.',
    reviewedAt: '2024-01-17T09:00:00Z',
  },
  {
    id: 'rev3',
    requestId: 'req3',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'Adobe Creative Suite is necessary for our marketing output quality. Approved for Carol and the marketing team.',
    reviewedAt: '2024-01-21T10:00:00Z',
  },
  {
    id: 'rev4',
    requestId: 'req4',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'Figma is a key design collaboration tool used across engineering and design. Approved.',
    reviewedAt: '2024-01-19T11:00:00Z',
  },
  {
    id: 'rev5',
    requestId: 'req6',
    reviewedBy: 'ceo1',
    decision: 'declined',
    reason: 'At $299/month, this is too costly without a detailed usage plan. Please resubmit with specific use cases and estimated cost breakdown per service used.',
    reviewedAt: '2024-01-23T10:00:00Z',
  },
  {
    id: 'rev6',
    requestId: 'req8',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'Notion is a great team productivity tool at a reasonable price. Approved for the marketing team.',
    reviewedAt: '2024-01-25T11:00:00Z',
  },
  {
    id: 'rev7',
    requestId: 'req10',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'Linear is an excellent engineering project management tool. Approved for the dev team.',
    reviewedAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'rev8',
    requestId: 'req11',
    reviewedBy: 'ceo1',
    decision: 'approved',
    reason: 'LinkedIn Sales Navigator is important for our outbound sales strategy and pipeline growth.',
    reviewedAt: '2024-01-15T10:00:00Z',
  },
  {
    id: 'rev9',
    requestId: 'req12',
    reviewedBy: 'ceo1',
    decision: 'declined',
    reason: 'We already have Adobe Creative Suite for the marketing team. Canva Pro would be a redundant expense. Please use the existing tools.',
    reviewedAt: '2024-01-13T09:00:00Z',
  },
]

export const MOCK_HR_ACTIONS: HrAction[] = [
  {
    id: 'ha1',
    requestId: 'req1',
    processedBy: 'hr1',
    cardLinked: true,
    cardLinkedNote: 'Successfully linked company Visa card ending in 4242. Subscription is active and auto-renewing.',
    tagIds: ['t1'],
    processedAt: '2024-01-17T14:00:00Z',
  },
  {
    id: 'ha2',
    requestId: 'req2',
    processedBy: 'hr1',
    cardLinked: true,
    cardLinkedNote: 'Linked company Mastercard ending in 8888. Salesforce Enterprise account configured and active.',
    tagIds: ['t2'],
    processedAt: '2024-01-18T11:00:00Z',
  },
  {
    id: 'ha3',
    requestId: 'req4',
    processedBy: 'hr1',
    cardLinked: true,
    cardLinkedNote: 'Card linked successfully. Figma Team workspace created and Alice added as admin.',
    tagIds: ['t1', 't3'],
    processedAt: '2024-01-20T09:00:00Z',
  },
  {
    id: 'ha4',
    requestId: 'req10',
    processedBy: 'hr1',
    cardLinked: true,
    cardLinkedNote: 'Linear subscription active. All engineering team members have been invited to the workspace.',
    tagIds: ['t1'],
    processedAt: '2024-01-21T15:00:00Z',
  },
  {
    id: 'ha5',
    requestId: 'req11',
    processedBy: 'hr1',
    cardLinked: true,
    cardLinkedNote: 'LinkedIn Sales Navigator active. Bob has been set as the account admin.',
    tagIds: ['t2'],
    processedAt: '2024-01-16T11:00:00Z',
  },
]
